apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    {{- include "xbot.labels" . | nindent 4 }}
data:
  {{- range $name, $value := .Values.secrets }}
  {{ $name }}: {{ $value | b64enc | quote }}
  {{- end }}
